### ISSUE TITLE
Existing jars in libs ordner are deleted

### ISSUE THREAD

**Issue by gandulf** [ksoichiro/gradle-eclipse-aar-plugin#1]
Hi, I've a project with some 3rd party jars in my libs ordner and if I use your plugin and generate the dependencies the libs ordner is deleted which deletes all my libs. 
And option to skip the deletion would be nice. It would be ok if I had to remove old verions of the dependncies jars manually.

**Comment by ksoichiro** [comment]
Thank you for trying this library and your request!
I'll add that option soon.

**Comment by ksoichiro** [comment]
Added new option named `cleanLibsDirectoryEnabled`.
If you'd like to skip deletion of `libs` directory, set it to `false`.

``` groovy
eclipseAar {
    cleanLibsDirectoryEnabled = false
}
```

**Comment by gandulf** [comment]
great, thank you very much

**Comment by ksoichiro** [comment]
Closing this issue.
Thanks again for your feedback!
