### ISSUE TITLE
Cannot have multiple dependencies with same library/module? name 

### ISSUE THREAD

**Issue by gandulf** [ksoichiro/gradle-eclipse-aar-plugin#2]
I don't know how to describe it correctly so I'll just give an example. I'm trying to use the following libraries in build.gradle:

...
dependencies {
    compile 'com.github.chrisbanes.photoview:library:1.2.3'
    compile 'com.github.amlcurran.showcaseview:library:5.0.0'
...
}

They both are named "library" and if I run your plugin only the last one of those two will get imported/created in aarDependencies

**Comment by ksoichiro** [comment]
Thank you for the feedback!
I got it.
I'll add `group` and `artifactId` to the dependency names like `com-github-chrisbanes-photoview-library-1.2.3`.
Please wait for it.

**Comment by ksoichiro** [comment]
I've finished it.
Jar names will be like `com.nineoldandroids-library-2.4.0.jar`.
Please try it, and don't forget to update `.classpath` and `project.properties`.

**Comment by gandulf** [comment]
The names are updated, but I still think there are some dependencies missing...

I have the following dependencies:
    compile 'com.github.chrisbanes.photoview:library:1.2.3'  
    compile 'com.github.amlcurran.showcaseview:library:5.0.0'

But only one (com.github.amlcurran.showcaseview-library-5.0.0) of them is added to the dependencies, the other seems to be ignored...

**Comment by ksoichiro** [comment]
Sorry, I'll fix this soon.

**Comment by ksoichiro** [comment]
I think it's fixed.

With these dependencies:

``` groovy
dependencies {
    compile 'com.github.chrisbanes.photoview:library:1.2.3'
    compile 'com.github.amlcurran.showcaseview:library:5.0.0'
}
```

the result will be like this:

``` xml
<classpathentry kind="lib" path="libs/com.android.support-support-v4-19.1.0.jar"/>
<classpathentry kind="lib" path="libs/com.github.chrisbanes.photoview-library-1.2.3.jar"/>
<classpathentry kind="lib" path="libs/com.github.amlcurran.showcaseview-library-5.0.0.jar"/>
```

``` properties
android.library.reference.1=aarDependencies/com.github.chrisbanes.photoview-library-1.2.3
android.library.reference.2=aarDependencies/com.github.amlcurran.showcaseview-library-5.0.0
```

**Comment by gandulf** [comment]
works fine

**Comment by ksoichiro** [comment]
Thanks for checking!
