### ISSUE TITLE
Updating dependency version causes problems

### ISSUE THREAD

**Issue by tobykurien** [ksoichiro/gradle-eclipse-aar-plugin#6]
If I have a dependency, e.g. `compile 'com.android.support:support-v4:21.0.0'` and then update that to `compile 'com.android.support:support-v4:21.0.3'`, and then re-run `gradle generateEclipseDependencies`, it should then remove old versions of the jars and AARs, update the new versions, and update the classpath accordingly. Currently, it will have old + new versions, causing problems when the dex files are being generated.

**Comment by ksoichiro** [comment]
Thank you for your feedback.
It should be handled by the plugin, please wait for the fix.

**Comment by ksoichiro** [comment]
@tobykurien I added a new option `jarDependenciesDir`, based on your idea.
If you set this option to some directory name, the plugin will handle it like `libs` directory.

``` groovy
eclipseAar {
    jarDependenciesDir = 'jarDependencies'
    cleanLibsDirectoryEnabled = true
}
```

If you these option and locate local JAR files to `jarDependencies` directory,
all of the files in `libs` are removed before generating JARs,
and local JARs and gradle dependency JARs will be copied to `libs`,
which solves version conflicts.

You can use it as `0.1.2-SNAPSHOT`.
Please set the repository for snapshot.

``` groovy
buildscript {
    repositories {
        mavenCentral()
        maven {
            url uri('https://oss.sonatype.org/content/repositories/snapshots/')
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.0.0'
        classpath 'com.github.ksoichiro:gradle-eclipse-aar-plugin:0.1.2-SNAPSHOT'
    }
}
```

**Comment by tobykurien** [comment]
I tested this. Almost working, there's one problem I picked up. If I update a library to a new version, the Eclipse classpath references both the new and old versions, so the compile fails. I then have to manually remove the references to the old JAR versions, as well as the old Android library references.

**Comment by ksoichiro** [comment]
Oops.. I missed your comment, sorry.
I'll check that issue.

**Comment by tobykurien** [comment]
I don't think this is a problem anymore, since you added support for cleaning up old versions

**Comment by ksoichiro** [comment]
OK, thanks!

**Comment by tobykurien** [comment]
Sorry, I tried this now, and it is indeed still a  problem that old (non-existing) JARs are still referenced in the Eclipse path.

**Comment by tobykurien** [comment]
seems to work in v0.1.3 after changing version.
