### ISSUE TITLE
Library project dependency

### ISSUE THREAD

**Issue by artyommironov** [ksoichiro/gradle-eclipse-aar-plugin#7]
I build android projects with gradle but use vim+eclim+eclipse to write code. I tried to generate eclipse dependencies with this plugin, but eclipse still can't resolve that dependency. It assumes that there is a jar file in library's bin folder, which is doesn't exists. How can I workaround it?

**Comment by tobykurien** [comment]
@kazufukurou there should actually be a jar file in the bin folder of the dependency if that dependent project compiled successfully. Fix any errors in the dependent project first (e.g. perhaps it's using an SDK version that's not installed?)

**Comment by artyommironov** [comment]
@tobykurien, I use gradle to build app. It doesn't create jar files in bin folder, instead it creates an aar somethere in build folder. I want to be able to create proper eclipse project config with one command, so I could work with eclim.
