### ISSUE TITLE
Jars from libs folder should not be added to .classpath

### ISSUE THREAD

**Issue by tobykurien** [ksoichiro/gradle-eclipse-aar-plugin#9]
Currently, Eclipse will automatically add all the jars from the `libs` folder, but this plugin also adds the jars to the classpath. This doesn't cause a compile issue, but causes an issue when packaging an Android app, because multiple jars define the same classes (due to duplicate jar dependencies). It is sufficient to just copy the jar files into `libs` without adding them to the classpath.

**Comment by tobykurien** [comment]
Any chance of releasing the current snapshot as a release? I'm using it in a few projects.

**Comment by ksoichiro** [comment]
@tobykurien Sorry! I'll release it soon.

**Comment by ksoichiro** [comment]
Just released v0.1.2 to 'https://oss.sonatype.org/content/repositories/releases/'.
It will be synced to Maven Central in 3 or 4 hours, maybe.

I'll handle this issue later. Sorry to have kept you waiting about this so long.

**Comment by ksoichiro** [comment]
@tobykurien You're right. We don't need to add jars in the libs folder to `.classpath`.
It's now fixed and released as `0.1.3-SNAPSHOT`.

**Comment by tobykurien** [comment]
@ksoichiro thanks, this works! Could you please release it?

**Comment by ksoichiro** [comment]
@tobykurien Thanks for checking! I've released v0.1.3 to 'https://oss.sonatype.org/content/repositories/releases/'.
It will be synced to Maven Central later.

**Comment by tobykurien** [comment]
Thanks this works well.
